#!/bin/bash

echo "🚀 Démarrage du serveur"

docker compose up -d

echo "🌱 Vérification de la BDD..."
docker compose exec php php sqlite/initialize.php
docker compose exec php php sqlite/seed-portfolio.php

echo "🌐 Serveur démarré sur http://localhost:8080"
